from __future__ import annotations

DEFAULT_MASK_LABEL = 1
DEFAULT_GEOMETRY_TOLERANCE = 1e-6
DEFAULT_FOLDS = 5
DEFAULT_RANDOM_STATE = 42
DEFAULT_VARIANCE_THRESHOLD = 0.0
DEFAULT_CORRELATION_THRESHOLD = 0.95
DEFAULT_TOP_K = 20
