setting:
  binWidth: 25
  resampledPixelSpacing: [1.0, 1.0, 1.0]
  interpolator: sitkBSpline
  correctMask: true
  geometryTolerance: 1e-6
  label: 1

imageType:
  Original: {}
  LoG:
    sigma: [1.0, 2.0, 3.0]
  Wavelet: {}

featureClass:
  firstorder: []
  shape: []
  glcm: []
  glrlm: []
  glszm: []
  gldm: []
  ngtdm: []
